### ISSUE TITLE
Some git link in j-edi-demo-packer.json has not worked any more

### ISSUE THREAD

**Issue by tudt949** [lamoni/j-edi-demo-package#1]
Two links as bellows don't work in  j-edi-demo-packer.json file when running packer command:
https://jedidemo:3996134aed0410cb7416612475ddc6e337b2afb1@github.com/Juniper/jedi-seed.git https://jedidemo:3996134aed0410cb7416612475ddc6e337b2afb1@github.com/Juniper/j-EDI.git

**Comment by lamoni** [comment]
@tudt949 looks like they moved or removed those repos, not sure why (I'm not on that team at Juniper anymore, so not sure if they've renamed it or something)
